### ISSUE TITLE
Html.Partial("_filename.cshtml") within a Html.Partial not finding the partial 

### ISSUE THREAD

**Issue by ghuntley** [statiqdev/Statiq.Web#899]
Maybe user error, maybe bug.

https://github.com/covidsafewatch/website/commit/ac703bdb91f6946c4608bb18ba01b55f4da1cda1#diff-ea6acb68c087d8157242beec2ec41309R69

```
PS C:\code\website> dotnet run -- preview
[INFO] Statiq version 1.0.0-beta.9+952e10e41c0cd2052f4fe5870de9da1d3c468083
[INFO] Root path:
       C:/code/website
[INFO] Input path(s):
       input
       theme/input
[INFO] Output path:
       output
[INFO] Temp path:
       temp
[INFO] Executing 10 pipelines (Archives, Assets, Content, Data, DirectoryMetadata, Feeds, Less, LinkValidation, Sass, Sitemap)
[INFO] Cleaned temp directory: temp
[INFO] Cleaned output directory: output
[INFO] -> DirectoryMetadata/Input » Starting DirectoryMetadata Input phase execution... (0 input document(s), 1 module(s))
[INFO] -> Data/Input » Starting Data Input phase execution... (0 input document(s), 1 module(s))
[INFO] -> Archives/Input » Starting Archives Input phase execution... (0 input document(s), 1 module(s))
[INFO] -> Content/Input » Starting Content Input phase execution... (0 input document(s), 1 module(s))
[INFO] -> Feeds/Input » Starting Feeds Input phase execution... (0 input document(s), 1 module(s))
[INFO] -> Assets/Process » Starting Assets Process phase execution... (0 input document(s), 1 module(s))
[INFO] -> Less/Input » Starting Less Input phase execution... (0 input document(s), 1 module(s))
[INFO] -> Sass/Input » Starting Sass Input phase execution... (0 input document(s), 1 module(s))
[INFO]    Data/Input » Finished Data Input phase execution (4 output document(s), 4499 ms)
[INFO]    Sass/Input » Finished Sass Input phase execution (4 output document(s), 1100 ms)
[INFO] -> Sass/Process » Starting Sass Process phase execution... (4 input document(s), 1 module(s))
[INFO]    Content/Input » Finished Content Input phase execution (46 output document(s), 4510 ms)
[INFO]    Feeds/Input » Finished Feeds Input phase execution (4 output document(s), 4508 ms)
[INFO]    Less/Input » Finished Less Input phase execution (0 output document(s), 2114 ms)
[INFO] -> Less/Process » Starting Less Process phase execution... (0 input document(s), 1 module(s))
[INFO]    DirectoryMetadata/Input » Finished DirectoryMetadata Input phase execution (0 output document(s), 4510 ms)
[INFO] -> DirectoryMetadata/Process » Starting DirectoryMetadata Process phase execution... (0 input document(s), 1 module(s))
[INFO]    Archives/Input » Finished Archives Input phase execution (46 output document(s), 4515 ms)
[INFO]    DirectoryMetadata/Process » Finished DirectoryMetadata Process phase execution (0 output document(s), 110 ms)
[INFO] -> Data/Process » Starting Data Process phase execution... (4 input document(s), 7 module(s))
[INFO] Less/Process » CacheDocuments » Resetting cache due to changes to dependent pipeline outputs
[INFO] Sass/Process » CacheDocuments » Resetting cache due to changes to dependent pipeline outputs
[INFO]    Less/Process » Finished Less Process phase execution (0 output document(s), 143 ms)
[INFO] -> Less/Output » Starting Less Output phase execution... (0 input document(s), 1 module(s))
[INFO]    Less/Output » Finished Less Output phase execution (0 output document(s), 21 ms)
[INFO]    Assets/Process » Finished Assets Process phase execution (18 output document(s), 3077 ms)
[INFO]    Data/Process » Finished Data Process phase execution (3 output document(s), 389 ms)
[INFO] -> Content/Process » Starting Content Process phase execution... (46 input document(s), 14 module(s))
[INFO]    Content/Process » Finished Content Process phase execution (5 output document(s), 1247 ms)
[INFO] -> Archives/Process » Starting Archives Process phase execution... (46 input document(s), 3 module(s))
[INFO]    Sass/Process » Finished Sass Process phase execution (4 output document(s), 1876 ms)
[INFO] -> Sass/Output » Starting Sass Output phase execution... (4 input document(s), 1 module(s))
[INFO]    Sass/Output » Finished Sass Output phase execution (4 output document(s), 72 ms)
[INFO]    Archives/Process » Finished Archives Process phase execution (5 output document(s), 10439 ms)
[INFO] -> Feeds/Process » Starting Feeds Process phase execution... (4 input document(s), 3 module(s))
[INFO]    Feeds/Process » Finished Feeds Process phase execution (2 output document(s), 459 ms)
[INFO] -> Content/PostProcess » Starting Content PostProcess phase execution... (5 input document(s), 3 module(s))
[INFO] -> Feeds/Output » Starting Feeds Output phase execution... (2 input document(s), 1 module(s))
[INFO] -> Data/Output » Starting Data Output phase execution... (3 input document(s), 2 module(s))
[INFO] -> Archives/PostProcess » Starting Archives PostProcess phase execution... (5 input document(s), 1 module(s))
[INFO] -> Sitemap/PostProcess » Starting Sitemap PostProcess phase execution... (0 input document(s), 1 module(s))
[INFO]    Data/Output » Finished Data Output phase execution (0 output document(s), 0 ms)
[INFO]    Feeds/Output » Finished Feeds Output phase execution (2 output document(s), 66 ms)
[INFO]    Sitemap/PostProcess » Finished Sitemap PostProcess phase execution (1 output document(s), 86 ms)
[INFO] -> Sitemap/Output » Starting Sitemap Output phase execution... (1 input document(s), 1 module(s))
[INFO] [Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager] User profile is available. Using 'C:\Users\ghuntley\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
[INFO]    Sitemap/Output » Finished Sitemap Output phase execution (1 output document(s), 9966 ms)
[ERRO] Content/PostProcess » RenderPostProcessTemplates » ExecuteIf » Error while executing module RenderRazor in Content/PostProcess: The partial view '_android-release-history.cshtml' was not found. The following locations were searched:
/input/senate-submissions/_android-release-history.cshtml
[ERRO] Content/PostProcess » RenderPostProcessTemplates » Error while executing module ExecuteIf in Content/PostProcess: The partial view '_android-release-history.cshtml' was not found. The following locations were searched:
/input/senate-submissions/_android-release-history.cshtml
[ERRO] Error while executing module RenderPostProcessTemplates in Content/PostProcess: The partial view '_android-release-history.cshtml' was not found. The following locations were searched:
/input/senate-submissions/_android-release-history.cshtml
[CRIT] Exception while executing pipeline Content/PostProcess: System.InvalidOperationException: The partial view '_android-release-history.cshtml' was not found. The following locations were searched:
/input/senate-submissions/_android-release-history.cshtml
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.PartialAsync(String partialViewName, Object model, ViewDataDictionary viewData)
   at Microsoft.AspNetCore.Mvc.Rendering.HtmlHelperPartialExtensions.Partial(IHtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at Microsoft.AspNetCore.Mvc.Rendering.HtmlHelperPartialExtensions.Partial(IHtmlHelper htmlHelper, String partialViewName)
   at AspNetCore.input_senate_submissions__layout.ExecuteAsync() in C:/code/website/input/senate-submissions/_layout.cshtml:line 69
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Statiq.Razor.RenderRazor.<>c__DisplayClass15_0.<<ExecuteContextAsync>g__RenderDocumentAsync|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Statiq.Common.ParallelAsyncExtensions.ParallelSelectAsync[TSource,TResult](IEnumerable`1 items, Func`2 asyncSelector, C   at Statiq.Common.Module.ExecuteAsync(IExecutionContext context)
   at Statiq.Common.Module.ExecuteAsync(IExecutionContext context)
s, ImmutableArray`1 inputs, ILogger logger)
   at Statiq.Core.ExecutionContext.ExecuteModulesAsync(IEnumerable`1 modules, IEnumerable`1 inputs)
   at Statiq.Core.ExecuteIf.ExecuteContextAsync(IExecutionContext context)
   at Statiq.Common.Module.ExecuteAsync(IExecutionContext context)
   at Statiq.Common.Module.ExecuteAsync(IExecutionContext context)
   at Statiq.Core.Engine.ExecuteModulesAsync(ExecutionContextData contextData, IExecutionContext parent, IEnumerable`1 modules, ImmutableArray`1 inputs, ILogger logger)
   at Statiq.Core.ExecutionContext.ExecuteModulesAsync(IEnumerable`1 modules, IEnumerable`1 inputs)
   at Statiq.Common.Module.ExecuteAsync(IExecutionContext context)
   at Statiq.Common.Module.ExecuteAsync(IExecutionContext context)
   at Statiq.Core.Engine.ExecuteModulesAsync(ExecutionContextData contextData, IExecutionContext parent, IEnumerable`1 modules, ImmutableArray`1 inputs, ILogger logger)
   at Statiq.Core.PipelinePhase.ExecuteAsync(Engine engine, ConcurrentDictionary`2 phaseResults)
[ERRO] Content/Output » Skipping pipeline due to dependency error
[INFO]    Archives/PostProcess » Finished Archives PostProcess phase execution (5 output document(s), 17404 ms)
[INFO] -> Archives/Output » Starting Archives Output phase execution... (5 input document(s), 1 module(s))
[INFO]    Archives/Output » Finished Archives Output phase execution (5 output document(s), 103 ms)
[CRIT] Error during execution
[ERRO] One or more errors occurred. (The partial view '_android-release-history.cshtml' was not found. The following locations were searched:
/input/senate-submissions/_android-release-history.cshtml)
[INFO] Cleaned temp directory: temp
```

**Comment by daveaglick** [comment]
Surprised I didn't already have an issue for this - I'm aware of the problem and have been intending to find/fix it in a release very soon. For anyone who stumbles on this in the meantime, root-relative paths will work. I'll use this as the tracking issue.
