### ISSUE TITLE
Error previewing CleanBlog using Statiq.Web beta.28

### ISSUE THREAD

**Issue by henrikrxn** [statiqdev/Statiq.Web#953]
Been experimenting with Statiq.Web over the weekend and I created a repository for repo that contains the code resulting from following the steps in the Statiq.Web "Quick Start" and then adding CleanBlog theme as git submodule

https://github.com/henrikrxn/StatiqWebQuickStartWithCleanBlogTheme

**I tried downgrading Statiq.Web to beta.27 and everything works without any issues.**

Also tried adding a couple of posts, but that makes no difference.

`dotnet --info` is at the end. Using latest .NET 5 SDK

From a Powershell 7.1.3 command prompt:

`dotnet run -- preview -l Debug --clean-mode Full`

on the repository mentioned above I get (partial output)

```
[DBUG] Content/PostProcess » RenderContentPostProcessTemplates » ExecuteIf » ExecuteIf » ExecuteIf » ExecuteConfig » RenderRazor » Compiling /_layout.cshtml
[ERRO] Content/PostProcess » RenderContentPostProcessTemplates » ExecuteIf » ExecuteIf » ExecuteIf » ExecuteConfig » RenderRazor » [E:/Experiments/StatiqWebQuickStartWithCleanBlogTheme/StatiqWebQuickStartWithCleanBlogTheme/input/index.md => index.html] One or more compilation failures occurred:

[ERRO] Content/PostProcess » RenderContentPostProcessTemplates » ExecuteIf » ExecuteIf » ExecuteIf » ExecuteConfig » RenderRazor » [E:/Experiments/StatiqWebQuickStartWithCleanBlogTheme/StatiqWebQuickStartWithCleanBlogTheme/input/no-posts/first-post.md => no-posts/first-post.html] One or more compilation failures occurred:

[ERRO] Content/PostProcess » RenderContentPostProcessTemplates » ExecuteIf » ExecuteIf » ExecuteIf » ExecuteConfig » RenderRazor » [E:/Experiments/StatiqWebQuickStartWithCleanBlogTheme/StatiqWebQuickStartWithCleanBlogTheme/input/no-posts/second-post.md => no-posts/second-post.html] One or more compilation failures occurred:

[DBUG] Exception while executing pipeline Content/PostProcess: Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.CompilationFailedException: One or more compilation failures occurred:

   at Statiq.Razor.StatiqViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Statiq.Razor.StatiqViewCompiler.<>c__DisplayClass17_0.<CompileAsync>b__0(CompilerCacheKey _)
   at Statiq.Common.ConcurrentCache`2.<>c__DisplayClass2_1.<GetOrAdd>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Statiq.Common.ConcurrentCache`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Statiq.Razor.CachingCompiler.GetOrAddCachedCompilation(CompilerCacheKey cacheKey, Func`2 valueFactory)
   at Statiq.Razor.StatiqViewCompiler.CompileAsync(String relativePath)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Statiq.Common.ConcurrentCache`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Lazy`1.get_Value()
   at Statiq.Razor.CachingCompiler.GetOrAddCachedCompilation(CompilerCacheKey cacheKey, Func`2 valueFactory)
   at Statiq.Razor.StatiqViewCompiler.CompileAsync(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromPath(String executingFilePath, String pagePath, Boolean isMainPage)
   at Statiq.Razor.StatiqViewCompiler.CompileAsync(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.GetPage(String executingFilePath, String pagePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.GetLayoutPage(ViewContext context, String executingFilePath, String layoutPath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromPath(String executingFilePath, String pagePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.GetLayoutPage(ViewContext context, String executingFilePath, String layoutPath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Statiq.Razor.RazorCompiler.RenderPageAsync(RenderRequest request)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Statiq.Razor.RazorCompiler.RenderPageAsync(RenderRequest request)
   at Statiq.Razor.RazorCompiler.RenderPageAsync(RenderRequest request)
   at Statiq.Razor.RazorService.RenderAsync(RenderRequest request)
   at Statiq.Razor.RazorService.RenderAsync(RenderRequest request)
   at Statiq.Razor.RazorService.RenderAsync(RenderRequest request)
   at Statiq.Razor.RenderRazor.<>c__DisplayClass16_0.<<ExecuteContextAsync>g__RenderDocumentAsync|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Statiq.Razor.RenderRazor.<>c__DisplayClass16_0.<<ExecuteContextAsync>g__RenderDocumentAsync|1>d.MoveNext()
[DBUG] Content/Output » Skipping pipeline due to dependency error
[DBUG] AnalyzeContent/Input » Skipping pipeline due to dependency error
[DBUG] AnalyzeContent/Process » Skipping pipeline due to dependency error
[DBUG] AnalyzeContent/PostProcess » Skipping pipeline due to dependency error
[DBUG] AnalyzeContent/Output » Skipping pipeline due to dependency error
[INFO] ========== Execution Summary =========`
```

```
PS E:\Experiments\StatiqWebQuickStartWithCleanBlogTheme\StatiqWebQuickStartWithCleanBlogTheme> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.203
 Commit:    383637d63f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.203\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  3.1.409 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
PS E:\Experiments\StatiqWebQuickStartWithCleanBlogTheme\StatiqWebQuickStartWithCleanBlogTheme>
```

**Comment by daveaglick** [comment]
Thanks for the report! The main new thing introduced in .28 was a disk-based caching layer. In testing it reduced build times from a cold start (after an initial generation) pretty dramatically. Even though I put it through paces on a bunch of sites and scenarios (including the stock getting started), looks like there may still be some bugs. I'll take a look ASAP - in the meantime you should be good to downgrade, you're not missing much other than the new (not functioning) cache.

**Comment by daveaglick** [comment]
I can reproduce, there appears to be two (related) problems...

First we get this cryptic exception during compilation (which is an inner aggregated exception which is why it doesn't show up until you debug and catch all exceptions):

```
"Exception of type 'Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.NativeIntegerTypeDecoder+ErrorTypeException' was thrown."
   at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.NativeIntegerTypeDecoder.TransformType(TypeSymbol type)
```

Then the compilation result has diagnostics that suggest references weren't properly referenced:

![image](https://user-images.githubusercontent.com/1020407/118490422-ec1faa00-b6eb-11eb-96c2-c3c02e12627d.png)

This all suggests in certain cases the caching conflicts with Razor compilation and emit. Still trying to figure out how since the first time through there aren't that many differences (it's only until _after_ the first execution that the compiled Razor assemblies are saved and restored).

**Comment by daveaglick** [comment]
I think this problem has less to do with the caching layer than with the way Razor compilation is now handled directly by Statiq (in order to support caching by emitting compiled Razor assemblies as a byte array). In the previous version, Razor compilation was called from inside the Razor engine (which then called Roslyn to do the compilation). Now that code has been copied into Statiq so that we can get the Roslyn compilation directly in order to emit the assembly (we only got the dynamic assembly when calling into the Razor engine for compilation).

In any case, even though the code is equivalent it looks like _for some_ (but not all) Razor code this causes a strange `NativeIntegerTypeDecoder+ErrorTypeException`. The best I can figure so far is there's a binding failure/type resolution failure somewhere. Like when calling from the Razor engine it was referencing one version of Roslyn but maybe Statiq is referencing a different version and there's a deep incompatibility somewhere.

I also found this issue, which seems like it might be loosely related: https://github.com/dotnet/roslyn/issues/49823

**Comment by daveaglick** [comment]
Here's the code where it's throwing:

https://github.com/dotnet/roslyn/blob/v3.8.0/src/Compilers/CSharp/Portable/Symbols/Metadata/PE/NativeIntegerTypeDecoder.cs
```cshap
private TypeSymbol TransformType(TypeSymbol type)
{
    switch (type.TypeKind)
    {
        case TypeKind.Array:
            return TransformArrayType((ArrayTypeSymbol)type);
        case TypeKind.Pointer:
            return TransformPointerType((PointerTypeSymbol)type);
        case TypeKind.FunctionPointer:
            return TransformFunctionPointerType((FunctionPointerTypeSymbol)type);
        case TypeKind.TypeParameter:
        case TypeKind.Dynamic:
            return type;
        case TypeKind.Class:
        case TypeKind.Struct:
        case TypeKind.Interface:
        case TypeKind.Delegate:
        case TypeKind.Enum:
            return TransformNamedType((NamedTypeSymbol)type);
        default:
            Debug.Assert(type.TypeKind == TypeKind.Error);
            throw new ErrorTypeException();
    }
}
```

The interesting thing is that it only appears to throw for an unknown `TypeKind` value. Statiq is using Roslyn 3.8 (and I also tried an update to 3.9 without any change in behavior) while the version of Razor Statiq references uses Roslyn 3.1.10 so maybe there's an incompatibility there (though really, we shouldn't be using much of the Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation functionality anymore anyway since Statiq is now handling compilation - maybe I'll see if that can be removed).

**Comment by daveaglick** [comment]
Got to the bottom of this - it really wasn't Roslyn at all. Because Statiq now intercepts compilation of layouts and partials (so they can be cached), a new global Razor project engine is instantiated for them (distinct from the one being used for individual views). Before it was a single project engine and so when we added the Razor engine phases that did things like populate using statements in the generated Razor file, those phases were also added for layouts and partials. Now with the separate layout/partial view compiler, the engine for those wasn't getting the phases added and so any layout/partial that referenced extra Statiq stuff failed to find those types (which is why some worked and some didn't).

Ensuring the Statiq Razor engine phases are added to the Razor project engine for the common global view compiler that deals with layouts and partials appears to resolve the problem. I'll release an update version with this hotfix ASAP.

Thanks again for the bug report!

**Comment by daveaglick** [comment]
New release is out and it should resolve this problem.

**Comment by daveaglick** [comment]
I'm still receiving reports of similar failures so I'm not sure this is totally resolved. Researching some more, but going to reopen this issue in the meantime (and transfer it to Statiq Framework since it's almost certainly a Razor engine problem in Framework).
