### ISSUE TITLE
"Object does not match target type" error on dotnet 6 rc1 on linux and macOS

### ISSUE THREAD

**Issue by phil-scott-78** [statiqdev/Statiq.Web#963]
Seeing this error compiling razor on dotnet 6 rc1 but only with Linux and macOS - `Object does not match target type`

Preview releases of dotnet 6 worked fine, but with the latest version this is failing on cshtml. 

You can see a full build output [here](https://github.com/spectreconsole/spectre.console/runs/3693241992?check_suite_focus=true#step:6:99) but here is the full stack trace. 

```
[DBUG] Exception while executing pipeline Archives/PostProcess: System.Reflection.TargetException: Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Statiq.Razor.StatiqViewCompiler.CreateCompilation(String generatedCode, String assemblyName)
   at Statiq.Razor.StatiqViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Statiq.Razor.RazorCompiler.GetCompilation(RazorProjectItem projectItem)
   at Statiq.Razor.RazorCompiler.<>c__DisplayClass11_0.<CompilePage>b__0(CompilerCacheKey _)
   at Statiq.Common.ConcurrentCache`2.<>c__DisplayClass2_1.<GetOrAdd>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at Statiq.Razor.CachingCompiler.GetOrAddCachedCompilation(CompilerCacheKey cacheKey, Func`2 valueFactory)
   at Statiq.Razor.RazorCompiler.CompilePage(RenderRequest request, Int32 contentCacheCode, RazorProjectItem projectItem)
   at Statiq.Razor.RazorCompiler.GetPageFromStreamAsync(IServiceProvider serviceProvider, RenderRequest request)
   at System.Lazy`1.CreateValue()
   at Statiq.Common.ConcurrentCache`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Statiq.Razor.CachingCompiler.GetOrAddCachedCompilation(CompilerCacheKey cacheKey, Func`2 valueFactory)
   at Statiq.Razor.RazorCompiler.CompilePage(RenderRequest request, Int32 contentCacheCode, RazorProjectItem projectItem)
   at Statiq.Razor.RazorCompiler.GetPageFromStreamAsync(IServiceProvider serviceProvider, RenderRequest request)
   at System.Lazy`1.CreateValue()
   at Statiq.Common.ConcurrentCache`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Statiq.Razor.CachingCompiler.GetOrAddCachedCompilation(CompilerCacheKey cacheKey, Func`2 valueFactory)
   at Statiq.Razor.RazorCompiler.CompilePage(RenderRequest request, Int32 contentCacheCode, RazorProjectItem projectItem)
   at Statiq.Razor.RazorCompiler.GetPageFromStreamAsync(IServiceProvider serviceProvider, RenderRequest request)
   at Statiq.Razor.RazorCompiler.RenderPageAsync(RenderRequest request)
   at Statiq.Razor.RazorCompiler.RenderPageAsync(RenderRequest request)
   at Statiq.Razor.RazorCompiler.RenderPageAsync(RenderRequest request)
   at Statiq.Razor.RazorCompiler.RenderPageAsync(RenderRequest request)
   at Statiq.Razor.RazorCompiler.RenderPageAsync(RenderRequest request)
   at Statiq.Razor.RazorCompiler.RenderPageAsync(RenderRequest request)
   at Statiq.Razor.RazorService.RenderAsync(RenderRequest request)
   at Statiq.Razor.RazorService.RenderAsync(RenderRequest request)
   at Statiq.Razor.RazorService.RenderAsync(RenderRequest request)
   at Statiq.Razor.RenderRazor.<>c__DisplayClass16_0.<<ExecuteContextAsync>g__RenderDocumentAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Statiq.Razor.RazorService.RenderAsync(RenderRequest request)
   at Statiq.Razor.RenderRazor.<>c__DisplayClass16_0.<<ExecuteContextAsync>g__RenderDocumentAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Statiq.Razor.RazorCompiler.RenderPageAsync(RenderRequest request)
   at Statiq.Razor.RazorService.RenderAsync(RenderRequest request)
   at Statiq.Razor.RazorService.RenderAsync(RenderRequest request)
   at Statiq.Razor.RazorCompiler.RenderPageAsync(RenderRequest request)
   at Statiq.Razor.RazorCompiler.RenderPageAsync(RenderRequest request)
   at Statiq.Razor.RazorCompiler.RenderPageAsync(RenderRequest request)
   at Statiq.Razor.RazorService.RenderAsync(RenderRequest request)
   at Statiq.Razor.RazorService.RenderAsync(RenderRequest request)
   at Statiq.Razor.RazorService.RenderAsync(RenderRequest request)
   at Statiq.Razor.RenderRazor.<>c__DisplayClass16_0.<<ExecuteContextAsync>g__RenderDocumentAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Statiq.Razor.RenderRazor.<>c__DisplayClass16_0.<<ExecuteContextAsync>g__RenderDocumentAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Statiq.Razor.RenderRazor.<>c__DisplayClass16_0.<<ExecuteContextAsync>g__RenderDocumentAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Statiq.Razor.RazorService.RenderAsync(RenderRequest request)
   at Statiq.Razor.RenderRazor.<>c__DisplayClass16_0.<<ExecuteContextAsync>g__RenderDocumentAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Statiq.Razor.RenderRazor.<>c__DisplayClass16_0.<<ExecuteContextAsync>g__RenderDocumentAsync|1>d.MoveNext()
```

**Comment by phil-scott-78** [comment]
To make sure it wasn't anything weird I was doing, because Lord knows I do weird things with Statiq, I built up the simplest reproduction I could. Sure enough ,same error. Reproduction is here - https://github.com/phil-scott-78/statiq-dotnet6

Got a bit less noise on this exception with the singular file when running `dotnet run -l Debug`

```
[ERRO] Content/PostProcess » RenderContentPostProcessTemplates » ExecuteIf » ExecuteIf » RenderRazor » [/Users/philscott/RiderProjects/StatiqNet6/input/index.cshtml => index.html] Object does not match target type.
[DBUG] Exception while executing pipeline Content/PostProcess: System.Reflection.TargetException: Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Statiq.Razor.StatiqViewCompiler.CreateCompilation(String generatedCode, String assemblyName)
   at Statiq.Razor.StatiqViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Statiq.Razor.RazorCompiler.GetCompilation(RazorProjectItem projectItem)
   at Statiq.Razor.RazorCompiler.<>c__DisplayClass11_0.<CompilePage>b__0(CompilerCacheKey _)
   at Statiq.Common.ConcurrentCache`2.<>c__DisplayClass2_1.<GetOrAdd>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Statiq.Common.ConcurrentCache`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Statiq.Razor.CachingCompiler.GetOrAddCachedCompilation(CompilerCacheKey cacheKey, Func`2 valueFactory)
   at Statiq.Razor.RazorCompiler.CompilePage(RenderRequest request, Int32 contentCacheCode, RazorProjectItem projectItem)
   at Statiq.Razor.RazorCompiler.GetPageFromStreamAsync(IServiceProvider serviceProvider, RenderRequest request)
   at Statiq.Razor.RazorCompiler.RenderPageAsync(RenderRequest request)
   at Statiq.Razor.RazorService.RenderAsync(RenderRequest request)
   at Statiq.Razor.RenderRazor.<>c__DisplayClass16_0.<<ExecuteContextAsync>g__RenderDocumentAsync|1>d.MoveNext()
```

**Comment by phil-scott-78** [comment]
Progress! On macOS I'm getting a `Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultViewCompiler` rather than the expected `Microsoft.AspNetCore.Mvc.Razor.Compilation.RuntimeViewCompiler` when calling `InnerViewCompilerProvider.GetCompiler()`.

Not sure why or how to move forward, but that's the scoop so far.

**Comment by phil-scott-78** [comment]
Sorry for the train of thought here, but I'm in the weeds and I wanted to dump what I found so hopefully someone smarter than me can pick up the trail, or at least tell me I'm on a wild goose chase here.

This [change](https://github.com/dotnet/aspnetcore/pull/35017/files#diff-940b7b75940c08518ebeb80c4d993d5972765f34ceba07f6158384fff8332160L17) is sus, especially considering this comment "This name is hardcoded in RazorRuntimeCompilationMvcCoreBuilderExtensions. Make sure it's updated if this is ever renamed." Looks like with this commit they merged the `DefaultViewCompiler` and `DefaultViewCompilerProvider` into one class. 

But tbh I'm struggling wrapping my head around whether this would cause my failure. With Statiq being compiled against 3.1 it feels like [this conditional](https://github.com/dotnet/aspnetcore/pull/35017/files#diff-8666d7268c5ed08d5180a40d60ff800bc8921b637d1a25d474a4034b81f44fb5R71) might not trigger with the new name causing the `TryAddSingleton` to skip the add because a previous instance never got removed. But that doesn't quite explain why it works in Windows and not macOS or Ubuntu. And I'm not sure why a different runtime would even cause this either.

**Comment by daveaglick** [comment]
Fantastic work getting to something we can investigate further. At first glance I think you’re definitely on to something and going down the right track. I’ll try to jump in and take a closer look tomorrow or in the next couple days. I do love a good debugging mystery :)

**Comment by daveaglick** [comment]
Going to move this issue to Framework since it's almost certainly with the Framework Razor extension.

Also for anyone else who ends up here with the same problem, a `global.json` locking .NET to 5 until this is resolved should help work around it (https://docs.microsoft.com/en-us/dotnet/core/versions/selection#the-sdk-uses-the-latest-installed-version):

```
{
  "sdk": {
    "version": "5.0.0"
  }
}
```
