### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by withinfocus** [statiqdev/Statiq.Web#984]
Hello -- when trying to execute Statiq e.g. `dotnet run` on an ARM64 device such as an M1 Mac you'll receive SASS compilation errors:

`[DBUG] Exception while executing pipeline Assets/Process: System.DllNotFoundException: Unable to load shared library 'libsass' or one of its dependencies.`

Stack trace:

```
   at SharpScss.LibSass.sass_alloc_memory(size_t size)
   at SharpScss.LibSass.StringUtf8.op_Implicit(String text)
   at SharpScss.Scss.FromCore(String fromStringOrFile, Boolean fromFile, ScssOptions options)
   at SharpScss.Scss.ConvertToCss(String scss, ScssOptions options)
   at Statiq.Sass.CompileSass.ExecuteInputAsync(IDocument input, IExecutionContext context)
   at Statiq.Common.Module.ExecuteInputFuncAsync(IDocument input, IExecutionContext context, Func`3 executeFunc)
```

Per https://github.com/xoofx/SharpScss/issues/19 this seems to have a troublesome future ahead of it, so does it make sense to abandon use of `SharpScss` in favor of something else, or even move to Dart Sass now that `libsass` is deprecated?

**Comment by daveaglick** [comment]
I'm not necessarily opposed to switching out the Sass implementation. In fact, several years ago I was using a different libsass wrapper and ended up switching to SharpScss due to limitations of that one. The challenge would be to find a library that 1) is easily bundled and deployed along with .NET packages (preferably in a way I don't have to maintain myself) and 2) supports similar features to what SharpScss does so that the Statiq modules still works the same way.

Neither of these requirements are particularly onerous, but to my knowledge SharpScss is basically the only option at this point. Going to Dart Sass would be neat - but I'd want to rely on a third-party wrapper for that, not deploy and maintain the wrapping code in Statiq. Am I missing any other options?

**Comment by withinfocus** [comment]
The Dart migration is certainly new-ish and https://github.com/Taritsyn/DartSassHost has recently been reinvigorated and might work. I also see https://github.com/koenvzeijl/AspNetCore.SassCompiler but its dependencies likely rule it out.

**Comment by daveaglick** [comment]
Both of those look interesting, and I'm glad to see some efforts in .NET to modernize Sass compiling, but I'm not sure either is stable enough or far enough along for our use. One thing I did find interesting is the use of a JavaScript engine to handle in-process compiling (as opposed to shelling out to Node). We already do that for some other things in Statiq so the approach might be a good fit. Perhaps there are some lessons learned here that could be applied to a custom implementation based on the JS libraries.

In any case, it's something I think would be worthwhile to explore, but probably doesn't rise to the top of my own priority list so it'll be a while before I have a chance to take a closer look. If you or someone else wants to experiment, I'd be interested in the results. Otherwise I'll add this to the backlog to take a look at after Statiq Docs ships later this year.
